# Your Wi-Fi SSID and password
wifi_ssid: "********"
wifi_password: "********"
wifi_bssid: "********"
pc_power_marker__ota_password: "********"
pc_power_marker__encryption_key: "********"
fallback_hotspot_password: '********'
meteostation__encryption_key: "********"
meteostation__ota_password: "********"
ir_hub__ota_password: "********"
ir_hub__encryption_key: "********"
ble_proxy__ota_password: "********"
ble_proxy__encryption_key: "********"
workroom_blinds__encryption_key: "********"
workroom_blinds__ota_password: "********"
