; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s3_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = lolin_s3_mini
framework = arduino
board_build.partitions = min_spiffs.csv
build_flags =
	-std=gnu++17
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DBOARD_HAS_PSRAM
	-I ${PROJECT_DIR}/include
	-I ${PROJECT_DIR}/.pio/esp_new_jpeg/include
	-DLV_CONF_PATH=\"${PROJECT_DIR}/include/lv_conf.h\"
	-L ${PROJECT_DIR}/.pio/esp_new_jpeg/lib/esp32s3
	-lesp_new_jpeg
build_unflags =
	-std=gnu++11
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	fastled/FastLED@^3.10.2
	tanakamasayuki/EspUsbHost@2.7.9
	lvgl/lvgl@^9.5.0
	bblanchon/ArduinoJson@^7
	https://github.com/debsahu/HARestAPI/archive/refs/heads/master.zip
	ayushsharma82/WebSerial@2.1.2
	ESP32Async/ESPAsyncWebServer@^3.9.0
	ESP32Async/AsyncTCP@^3.4.0
monitor_speed = 115200
extra_scripts = pre:scripts/fetch_esp_new_jpeg.py

[env:lolin_s3_mini_ota]
extends = env:lolin_s3_mini
upload_protocol = espota
upload_port = pocketbook-frame.local
upload_flags =
	--timeout=60
